### ISSUE TITLE
net.fit example

### ISSUE THREAD

**Issue by DrSleep** [classner/barrista#2]
Hello!

I have some problems when running the net.fit() example from the documentation page: http://classner.github.io/barrista/usage.html
1. perforce = JSONLogger(json_filename='test.json') execution gives the TypeError: **init**() got an unexpected keyword argument 'json_filename'. So I looked up  the source code and 'example.py', and it seems that the usage of JSONLogger has changed, as well as fit().
2. Trying to run example.py I encountered the following error during net.fit(...): ArgumentError: Python argument types in
   SGDSolver.**init**(SGDSolver, str, Net)
   did not match C++ signature:
   **init**(_object*, std::string)

Would be great if you can help me to solve the problem.

**Comment by DrSleep** [comment]
Turned out I forgot to re-build caffe...

**Comment by classner** [comment]
Thanks for pointing out the interface change! I updated the doc on `unstable`, also in other places. Will be on master and the homepage soon!
